name: Luna CI/CD
on: 
  pull_request:
    branches:
    - main
    - develop

  push:
    branches:
    - develop
    - feature/*

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
jobs:
  Build:
    runs-on: ubuntu-latest
    container: dawidblom/luna:latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Build Project
      run: scripts/Build.sh  
      
    - name: Static Code Analysis
      run: scripts/StaticCodeAnalysis.sh
      
  Tests:
    runs-on: ubuntu-latest
    container: dawidblom/luna:latest  
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Unit Tests
      run: |
        cd test
        make -s -f Makefile UnitTests
        ./UnitTests -c -v
      env:
        CPPUTEST_HOME: ${{ vars.CPPUTEST_HOME }}

    - name: Code Coverage
      run: scripts/CodeCoverage.sh

